import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { Container } from "./Container";
import { PlatformProvider } from "@/context/PlatformContext";

const mulish = Mulish({
  variable:"--font-mulish",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PlatformProvider>
      <body
        className={`${mulish.variable} antialiased`}
      >
        <Container>
        {children}
        </Container>
      </body>
      </PlatformProvider>
    </html>
  );
}
